// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[username].js";
import * as $1 from "./routes/_404.js";
import * as $2 from "./routes/_500.js";
import * as $3 from "./routes/form.jsx";
import * as $4 from "./routes/handler-json.js";
import * as $5 from "./routes/handler.jsx";
import * as $6 from "./routes/html.js";
import * as $7 from "./routes/index.js";
import * as $8 from "./routes/template.js";

const manifest = {
  routes: {
    "./routes/[username].js": $0,
    "./routes/_404.js": $1,
    "./routes/_500.js": $2,
    "./routes/form.jsx": $3,
    "./routes/handler-json.js": $4,
    "./routes/handler.jsx": $5,
    "./routes/html.js": $6,
    "./routes/index.js": $7,
    "./routes/template.js": $8,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
